server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garage
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
