server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      routes:
        - id: vehicle-service-route
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**
          filters:
            - StripPrefix=1
