server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: vehicle-service-route
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**
          filters:
            - StripPrefix=1
        - id: garage-service-route
          uri: lb://GARAGE-SERVICE
          predicates:
            - Path=/garage-service/**
          filters:
            - StripPrefix=1
        - id: client-service-route
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client-service/**
          filters:
            - StripPrefix=1
        - id: repair-service-route
          uri: lb://REPAIR-SERVICE
          predicates:
            - Path=/repair-service/**
          filters:
            - StripPrefix=1
