server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registry-fetch-interval-seconds: 10
    fetch-registry: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garage
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
metrics:
    tags:
      application: ${spring.application.name}
